[package]
name = "xh"
version = "0.8.1"
authors = ["ducaale <sharaf.13@hotmail.com>"]
edition = "2018"
license = "MIT"
description = "Yet another HTTPie clone"
documentation = "https://github.com/ducaale/xh"
homepage = "https://github.com/ducaale/xh"
repository = "https://github.com/ducaale/xh"
readme = "README.md"

[dependencies]
ansi_term = "0.12"
anyhow = "1.0.38"
atty = "0.2"
encoding_rs = "0.8.28"
encoding_rs_io = "0.1.7"
exit_status = "0.1.0"
indicatif = "0.15.0"
lazy_static = "1.4.0"
memchr = "2.3.4"
mime = "0.3.16"
mime2ext = "0.1.0"
pem = "0.8.2"
regex = "1"
reqwest = { version = "0.11.1", default-features = false, features = ["rustls-tls", "json", "gzip", "brotli", "multipart", "blocking", "socks"] }
rpassword = "5.0.0"
serde = "1.0"
serde_json = "1.0"
serde_urlencoded = "0.7.0"
shell-escape = "0.1.5"
structopt = "0.3"

[dependencies.syntect]
version = "4.4"
default-features = false
features = ["parsing", "html", "yaml-load", "dump-load", "dump-create", "regex-onig"]

[dev-dependencies]
# Some are only needed for the `integration-tests` feature, but dev-dependencies can't be optional
assert_cmd = "1.0"
assert_matches = "1.4.0"
indoc = "1.0"
predicates = "1.0.7"
httpmock = "0.5.5"
curl = { version = "0.4.34", features = ["static-ssl"] }
tempfile = "3.2.0"

[features]
default = ["integration-tests"]

integration-tests = []

[build-dependencies]
syntect = { version = "4.4", default-features = false }
